In [1]:
import numpy as np

In [4]:
np.random.randint(10, size = 20).reshape(5, 4)

array([[0, 9, 3, 5],
       [4, 3, 0, 4],
       [6, 4, 9, 8],
       [1, 1, 3, 9],
       [9, 8, 0, 3]])

In [5]:
a = np.random.randint(10, size = 20).reshape(5, 4)

In [6]:
a

array([[2, 8, 3, 5],
       [4, 7, 4, 6],
       [1, 7, 6, 1],
       [1, 9, 7, 3],
       [7, 5, 1, 6]])

In [7]:
b = np.random.randint(10, size = 20).reshape(5, 4)

In [8]:
b

array([[4, 9, 0, 0],
       [1, 2, 9, 1],
       [7, 7, 2, 9],
       [1, 1, 2, 8],
       [5, 3, 7, 7]])

In [9]:
a + b

array([[ 6, 17,  3,  5],
       [ 5,  9, 13,  7],
       [ 8, 14,  8, 10],
       [ 2, 10,  9, 11],
       [12,  8,  8, 13]])

In [10]:
a - b

array([[-2, -1,  3,  5],
       [ 3,  5, -5,  5],
       [-6,  0,  4, -8],
       [ 0,  8,  5, -5],
       [ 2,  2, -6, -1]])

In [11]:
a * b

array([[ 8, 72,  0,  0],
       [ 4, 14, 36,  6],
       [ 7, 49, 12,  9],
       [ 1,  9, 14, 24],
       [35, 15,  7, 42]])

In [12]:
b / a

array([[2.        , 1.125     , 0.        , 0.        ],
       [0.25      , 0.28571429, 2.25      , 0.16666667],
       [7.        , 1.        , 0.33333333, 9.        ],
       [1.        , 0.11111111, 0.28571429, 2.66666667],
       [0.71428571, 0.6       , 7.        , 1.16666667]])

In [13]:
np.mat(a)

matrix([[2, 8, 3, 5],
        [4, 7, 4, 6],
        [1, 7, 6, 1],
        [1, 9, 7, 3],
        [7, 5, 1, 6]])

In [14]:
np.mat(b)

matrix([[4, 9, 0, 0],
        [1, 2, 9, 1],
        [7, 7, 2, 9],
        [1, 1, 2, 8],
        [5, 3, 7, 7]])

In [15]:
A = np.mat(a)

In [16]:
B = np.mat(b)

In [17]:
A

matrix([[2, 8, 3, 5],
        [4, 7, 4, 6],
        [1, 7, 6, 1],
        [1, 9, 7, 3],
        [7, 5, 1, 6]])

In [18]:
B

matrix([[4, 9, 0, 0],
        [1, 2, 9, 1],
        [7, 7, 2, 9],
        [1, 1, 2, 8],
        [5, 3, 7, 7]])

In [19]:
A * B

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [20]:
A + B

matrix([[ 6, 17,  3,  5],
        [ 5,  9, 13,  7],
        [ 8, 14,  8, 10],
        [ 2, 10,  9, 11],
        [12,  8,  8, 13]])

In [21]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
sum(a)

array([15, 36, 21, 21])

In [23]:
sum(a[0])

18

In [24]:
sum(a[:,0])

15